import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import test from 'node:test'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cli = join(packageRoot, 'bin/synced-fluid.mjs')

function tempProject() {
  const cwd = mkdtempSync(join(tmpdir(), 'synced-fluid-test-'))
  mkdirSync(join(cwd, 'src'), { recursive: true })
  mkdirSync(join(cwd, 'node_modules/@synced'), { recursive: true })
  symlinkSync(packageRoot, join(cwd, 'node_modules/@synced/fluid'), 'dir')
  writeFileSync(
    join(cwd, 'package.json'),
    JSON.stringify(
      {
        type: 'module',
        scripts: {},
        dependencies: {
          '@synced/fluid': 'file:../synced-fluid',
        },
      },
      null,
      2
    ) + '\n'
  )
  return cwd
}

function run(args, options = {}) {
  return execFileSync('node', [cli, ...args], {
    cwd: packageRoot,
    encoding: 'utf8',
    ...options,
  })
}

test('init scaffolds config, CSS entry, generated CSS, and scripts', () => {
  const cwd = tempProject()

  const output = run(['init', '--cwd', cwd, '--preset', 'vite', '--safelist', 'hidden flex'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssEntry = readFileSync(join(cwd, 'src/synced-fluid.css'), 'utf8')
  const generated = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  const pkg = JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8'))

  assert.match(config, /scan: \['src'\]/)
  assert.match(config, /import \{ themePresets \} from '@synced\/fluid\/presets'/)
  assert.match(config, /theme: themePresets\.synced/)
  assert.doesNotMatch(config, /includeApp/)
  assert.match(config, /safelist: \['hidden', 'flex'\]/)
  assert.match(cssEntry, /@import "@synced\/fluid\/styles\.css"/)
  assert.match(cssEntry, /@import "@synced\/fluid\/app\.css"/)
  assert.match(generated, /Generated by @synced\/fluid/)
  assert.equal(pkg.scripts['fluid:build'], 'synced-fluid build')
  assert.equal(pkg.scripts['fluid:check'], 'synced-fluid build --check')
  assert.equal(pkg.scripts['fluid:doctor'], 'synced-fluid doctor')
  assert.match(output, /app\.css removes raw link underlines and list markers/)
})

test('init can opt out of app defaults', () => {
  const cwd = tempProject()

  const output = run(['init', '--cwd', cwd, '--preset', 'vite', '--no-app'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssEntry = readFileSync(join(cwd, 'src/synced-fluid.css'), 'utf8')

  assert.doesNotMatch(config, /includeApp/)
  assert.doesNotMatch(cssEntry, /@synced\/fluid\/app\.css/)
  assert.match(output, /run synced-fluid add app/)
})

test('add app inserts the optional app layer import', () => {
  const cwd = tempProject()

  run(['init', '--cwd', cwd, '--preset', 'vite', '--no-app'])
  run(['add', 'app', '--cwd', cwd])

  const cssEntry = readFileSync(join(cwd, 'src/synced-fluid.css'), 'utf8')
  assert.match(cssEntry, /@import "@synced\/fluid\/styles\.css";\n@import "@synced\/fluid\/app\.css";/)
})

test('build emits safelist classes and theme overrides', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sf-container text-primary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
  safelist: ['hidden'],
  theme: {
    fonts: { sans: 'Example Sans, sans-serif' },
    colours: { primary: 'oklch(70% 0.2 40)' },
    layout: { containerMax: '68rem' },
  },
})
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  assert.match(css, /--sf-font-sans: Example Sans, sans-serif;/)
  assert.match(css, /--sf-colour-primary: oklch\(70% 0\.2 40\);/)
  assert.match(css, /--grid-max-width: 68rem;/)
  assert.match(css, /\[class~="hidden"\]\{display:none\}/)
  assert.match(css, /\[class~="text-primary"\]\{color:var\(--color-primary\)\}/)
})

test('strict mode rejects responsive variants by default', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sm:flex"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
})
`
  )

  const result = spawnSync('node', [cli, 'build', '--cwd', cwd], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /Unsupported class tokens: 1/)
  assert.match(result.stderr, /sm:flex/)
})

test('responsiveVariants enables migration breakpoint classes', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sm:flex"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
  responsiveVariants: true,
})
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  assert.match(css, /@media \(min-width: 36rem\)\{\[class~="sm:flex"\]\{display:flex\}\}/)
})

test('doctor passes a configured project', () => {
  const cwd = tempProject()
  run(['init', '--cwd', cwd, '--preset', 'vite'])
  run(['build', '--cwd', cwd])

  const output = run(['doctor', '--cwd', cwd])

  assert.match(output, /pass @synced\/fluid is installed/)
  assert.match(output, /pass fluid:doctor script is configured/)
  assert.match(output, /pass Strict fluid mode is enabled/)
  assert.match(output, /pass Core stylesheet import found/)
})

test('init supports theme aliases', () => {
  const cwd = tempProject()

  run(['init', '--cwd', cwd, '--preset', 'vite', '--theme', 'neutral-saas'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  assert.match(config, /theme: themePresets\.neutralSaas/)
})

test('init supports WordPress themes with enqueue-ready CSS output', () => {
  const cwd = tempProject()
  mkdirSync(join(cwd, 'templates'), { recursive: true })
  mkdirSync(join(cwd, 'parts'), { recursive: true })
  writeFileSync(join(cwd, 'functions.php'), '<?php\n')

  run(['init', '--cwd', cwd, '--preset', 'wordpress'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssOutput = readFileSync(join(cwd, 'assets/css/synced-fluid.css'), 'utf8')

  assert.match(config, /scan: \['templates', 'parts', 'src'\]/)
  assert.match(config, /out: 'assets\/css\/synced-fluid.css'/)
  assert.match(config, /includeCore: true/)
  assert.match(cssOutput, /Generated by @synced\/fluid/)
  assert.equal(existsSync(join(cwd, 'src/synced-fluid.css')), false)

  run(['build', '--cwd', cwd])
  const builtCssOutput = readFileSync(join(cwd, 'assets/css/synced-fluid.css'), 'utf8')
  assert.match(builtCssOutput, /\.sf-skip-link/)
  assert.match(builtCssOutput, /:where\(\.sf-visually-hidden, \.sr-only\)/)

  const doctor = run(['doctor', '--cwd', cwd])
  assert.match(doctor, /pass Core CSS is included in generated output/)
})

test('init include-core writes a single importable CSS output', () => {
  const cwd = tempProject()

  run(['init', '--cwd', cwd, '--preset', 'vite', '--include-core'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssOutput = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')

  assert.match(config, /includeCore: true/)
  assert.match(config, /includeApp: true/)
  assert.match(cssOutput, /Generated by @synced\/fluid/)
  assert.equal(existsSync(join(cwd, 'src/synced-fluid.css')), false)
})

test('tokens command prints machine-readable starter surface', () => {
  const output = run(['tokens', '--json'])
  const tokens = JSON.parse(output)

  assert.ok(tokens.themePresets.includes('neutral-saas'))
  assert.ok(tokens.starterClasses.layout.includes('sf-split'))
  assert.ok(tokens.starterClasses.components.includes('sf-section-header'))
  assert.ok(tokens.starterClasses.utilities.includes('sr-only'))
  assert.ok(tokens.starterClasses.utilities.includes('sf-skip-link'))
  assert.ok(tokens.starterClasses.utilities.includes('sf-link-plain'))
  assert.ok(tokens.colours.semantic.includes('primary'))
})

test('package exposes modular CSS layer files', () => {
  const pkg = JSON.parse(readFileSync(join(packageRoot, 'package.json'), 'utf8'))
  const files = ['tokens.css', 'reset.css', 'base.css', 'app.css', 'layout.css', 'components.css', 'utilities.css', 'styles.css']

  for (const file of files) {
    assert.equal(pkg.exports[`./${file}`], `./${file}`)
    assert.match(readFileSync(join(packageRoot, file), 'utf8'), /@layer reset, tokens, base, app, layout, components, utilities;/)
  }

  const baseCss = readFileSync(join(packageRoot, 'base.css'), 'utf8')
  const appCss = readFileSync(join(packageRoot, 'app.css'), 'utf8')
  const utilitiesCss = readFileSync(join(packageRoot, 'utilities.css'), 'utf8')
  assert.match(baseCss, /text-decoration-color: color-mix\(in oklch, currentColor 55%, transparent\)/)
  assert.doesNotMatch(baseCss, /:where\(a\) \{ color: inherit; text-decoration: none;/)
  assert.match(appCss, /@layer app/)
  assert.match(appCss, /text-decoration: none/)
  assert.match(appCss, /list-style: none/)
  assert.match(utilitiesCss, /:where\(\.sf-visually-hidden, \.sr-only\)/)
  assert.match(utilitiesCss, /\.sf-skip-link/)
  assert.match(utilitiesCss, /\.sf-list-reset/)
  assert.match(utilitiesCss, /\.sf-link-plain/)
})

test('invalid config fails with actionable errors', () => {
  const cwd = tempProject()
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: 'src',
  out: 42,
  responsiveVariants: 'yes',
  theme: {
    colours: ['bad'],
    layout: { columns: 0 },
  },
}
`
  )

  const result = spawnSync('node', [cli, 'build', '--cwd', cwd], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /Invalid Synced Fluid config/)
  assert.match(result.stderr, /scan must be an array of strings/)
  assert.match(result.stderr, /out must be a string/)
  assert.match(result.stderr, /responsiveVariants must be a boolean/)
  assert.match(result.stderr, /theme.colours must be an object/)
  assert.match(result.stderr, /theme.layout.columns must be a positive number/)
})

test('build creates missing output directories atomically', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="text-primary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['src'],
  out: 'generated/css/synced-fluid.css',
}
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'generated/css/synced-fluid.css'), 'utf8')
  assert.match(css, /Generated by @synced\/fluid/)
  assert.match(css, /\[class~="text-primary"\]\{color:var\(--color-primary\)\}/)
})

test('build scans WordPress PHP templates', () => {
  const cwd = tempProject()
  mkdirSync(join(cwd, 'templates'), { recursive: true })
  writeFileSync(join(cwd, 'templates/front-page.php'), '<section class="text-primary animate-pulse"></section>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['templates'],
  out: 'assets/css/synced-fluid.css',
  includeCore: true,
}
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'assets/css/synced-fluid.css'), 'utf8')
  assert.match(css, /\[class~="text-primary"\]\{color:var\(--color-primary\)\}/)
  assert.match(css, /@keyframes sf-pulse/)
})

test('build omits unused generated animation and gradient helpers', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="text-primary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
}
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  assert.doesNotMatch(css, /@keyframes sf-pulse/)
  assert.doesNotMatch(css, /bg-gradient-to-r/)
})

test('runtime cx helper is dependency-free and handles common class values', async () => {
  const { cx } = await import(pathToFileURL(join(packageRoot, 'dist/index.js')).href)

  assert.equal(cx('sf-card', ['text-primary', false, ['font-bold']], { hidden: false, flex: true }), 'sf-card text-primary font-bold flex')
})

test('build warns about missing scan directories', () => {
  const cwd = tempProject()
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['missing'],
  out: 'src/synced-fluid.generated.css',
}
`
  )

  const result = spawnSync('node', [cli, 'build', '--cwd', cwd, '--no-fail-on-unsupported'], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.equal(result.status, 0)
  assert.match(result.stderr, /Scan directories not found: missing/)
})
