import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import test from 'node:test'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cli = join(packageRoot, 'bin/synced-fluid.mjs')

function tempProject() {
  const cwd = mkdtempSync(join(tmpdir(), 'synced-fluid-test-'))
  mkdirSync(join(cwd, 'src'), { recursive: true })
  mkdirSync(join(cwd, 'node_modules/@synced'), { recursive: true })
  symlinkSync(packageRoot, join(cwd, 'node_modules/@synced/fluid'), 'dir')
  writeFileSync(
    join(cwd, 'package.json'),
    JSON.stringify(
      {
        type: 'module',
        scripts: {},
        dependencies: {
          '@synced/fluid': 'file:../synced-fluid',
        },
      },
      null,
      2
    ) + '\n'
  )
  return cwd
}

function run(args, options = {}) {
  return execFileSync('node', [cli, ...args], {
    cwd: packageRoot,
    encoding: 'utf8',
    ...options,
  })
}

test('init scaffolds config, CSS entry, generated CSS, and scripts', () => {
  const cwd = tempProject()

  const output = run(['init', '--cwd', cwd, '--preset', 'vite', '--safelist', 'hidden flex'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssEntry = readFileSync(join(cwd, 'src/synced-fluid.css'), 'utf8')
  const generated = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  const pkg = JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8'))

  assert.match(config, /scan: \['src'\]/)
  assert.match(config, /import \{ themePresets \} from '@synced\/fluid\/presets'/)
  assert.match(config, /theme: themePresets\.synced/)
  assert.doesNotMatch(config, /includeApp/)
  assert.match(config, /safelist: \['hidden', 'flex'\]/)
  assert.match(cssEntry, /@import "@synced\/fluid\/styles\.css"/)
  assert.match(cssEntry, /@import "@synced\/fluid\/app\.css"/)
  assert.match(generated, /Generated by @synced\/fluid/)
  assert.equal(pkg.scripts['fluid:build'], 'synced-fluid build')
  assert.equal(pkg.scripts['fluid:check'], 'synced-fluid build --check')
  assert.equal(pkg.scripts['fluid:doctor'], 'synced-fluid doctor')
  assert.equal(pkg.scripts['fluid:lint'], 'synced-fluid lint')
  assert.equal(pkg.scripts['fluid:watch'], 'synced-fluid watch')
  assert.match(output, /app\.css removes raw link underlines and list markers/)
})

test('init can opt out of app defaults', () => {
  const cwd = tempProject()

  const output = run(['init', '--cwd', cwd, '--preset', 'vite', '--no-app'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssEntry = readFileSync(join(cwd, 'src/synced-fluid.css'), 'utf8')

  assert.doesNotMatch(config, /includeApp/)
  assert.doesNotMatch(cssEntry, /@synced\/fluid\/app\.css/)
  assert.match(output, /run synced-fluid add app/)
})

test('add app inserts the optional app layer import', () => {
  const cwd = tempProject()

  run(['init', '--cwd', cwd, '--preset', 'vite', '--no-app'])
  run(['add', 'app', '--cwd', cwd])

  const cssEntry = readFileSync(join(cwd, 'src/synced-fluid.css'), 'utf8')
  assert.match(cssEntry, /@import "@synced\/fluid\/styles\.css";\n@import "@synced\/fluid\/app\.css";/)
})

test('build emits safelist classes and theme overrides', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sf-container text-primary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
  safelist: ['hidden'],
  theme: {
    fonts: { sans: 'Example Sans, sans-serif' },
    colours: { primary: 'oklch(70% 0.2 40)' },
    layout: { containerMax: '68rem' },
  },
})
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  assert.match(css, /--sf-font-sans: Example Sans, sans-serif;/)
  assert.match(css, /--sf-colour-primary: oklch\(70% 0\.2 40\);/)
  assert.match(css, /--grid-max-width: 68rem;/)
  assert.match(css, /\[class~="hidden"\]\{display:none\}/)
  assert.match(css, /\[class~="text-primary"\]\{color:var\(--color-primary\)\}/)
})

test('strict mode rejects responsive variants by default', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sm:flex"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
})
`
  )

  const result = spawnSync('node', [cli, 'build', '--cwd', cwd], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /Unsupported class tokens: 1/)
  assert.match(result.stderr, /sm:flex/)
})

test('responsiveVariants enables migration breakpoint classes', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sm:flex"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
  responsiveVariants: true,
})
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  assert.match(css, /@media \(min-width: 36rem\)\{\[class~="sm:flex"\]\{display:flex\}\}/)
})

test('doctor passes a configured project', () => {
  const cwd = tempProject()
  run(['init', '--cwd', cwd, '--preset', 'vite'])
  run(['build', '--cwd', cwd])

  const output = run(['doctor', '--cwd', cwd])

  assert.match(output, /pass @synced\/fluid is installed/)
  assert.match(output, /pass fluid:doctor script is configured/)
  assert.match(output, /pass Strict fluid mode is enabled/)
  assert.match(output, /pass Core stylesheet import found/)
})

test('doctor finds core imports in root CSS entries', () => {
  const cwd = tempProject()
  run(['init', '--cwd', cwd, '--preset', 'plain'])
  run(['build', '--cwd', cwd])

  const output = run(['doctor', '--cwd', cwd])

  assert.match(output, /pass Core stylesheet import found/)
})

test('init supports theme aliases', () => {
  const cwd = tempProject()

  run(['init', '--cwd', cwd, '--preset', 'vite', '--theme', 'neutral-saas'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  assert.match(config, /theme: themePresets\.neutralSaas/)
})

test('theme presets include production-ready semantic and component tokens', async () => {
  const { themePresets } = await import(pathToFileURL(join(packageRoot, 'src/presets.mjs')).href)

  for (const [name, preset] of Object.entries(themePresets)) {
    assert.ok(preset.fonts?.sans, `${name} has a sans font`)
    assert.ok(preset.fonts?.display, `${name} has a display font`)
    assert.ok(preset.colours?.background, `${name} has a background colour`)
    assert.ok(preset.colours?.foreground, `${name} has a foreground colour`)
    assert.ok(preset.colours?.surface, `${name} has a surface colour`)
    assert.ok(preset.colours?.primary, `${name} has a primary colour`)
    assert.ok(preset.colours?.link, `${name} has a link colour`)
    assert.ok(preset.colours?.ring, `${name} has a focus ring colour`)
    assert.ok(preset.components?.button, `${name} has button component tokens`)
    assert.ok(preset.components?.card, `${name} has card component tokens`)
    assert.ok(preset.components?.input, `${name} has input component tokens`)
  }
})

test('init supports WordPress themes with enqueue-ready CSS output', () => {
  const cwd = tempProject()
  mkdirSync(join(cwd, 'templates'), { recursive: true })
  mkdirSync(join(cwd, 'parts'), { recursive: true })
  writeFileSync(join(cwd, 'functions.php'), '<?php\n')

  run(['init', '--cwd', cwd, '--preset', 'wordpress'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssOutput = readFileSync(join(cwd, 'assets/css/synced-fluid.css'), 'utf8')

  assert.match(config, /scan: \['templates', 'parts', 'src'\]/)
  assert.match(config, /out: 'assets\/css\/synced-fluid.css'/)
  assert.match(config, /includeCore: true/)
  assert.match(cssOutput, /Generated by @synced\/fluid/)
  assert.equal(existsSync(join(cwd, 'src/synced-fluid.css')), false)

  run(['build', '--cwd', cwd])
  const builtCssOutput = readFileSync(join(cwd, 'assets/css/synced-fluid.css'), 'utf8')
  assert.match(builtCssOutput, /\.sf-skip-link/)
  assert.match(builtCssOutput, /:where\(\.sf-visually-hidden, \.sr-only\)/)

  const doctor = run(['doctor', '--cwd', cwd])
  assert.match(doctor, /pass Core CSS is included in generated output/)
})

test('init include-core writes a single importable CSS output', () => {
  const cwd = tempProject()

  run(['init', '--cwd', cwd, '--preset', 'vite', '--include-core'])

  const config = readFileSync(join(cwd, 'synced-fluid.config.mjs'), 'utf8')
  const cssOutput = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')

  assert.match(config, /includeCore: true/)
  assert.match(config, /includeApp: true/)
  assert.match(cssOutput, /Generated by @synced\/fluid/)
  assert.equal(existsSync(join(cwd, 'src/synced-fluid.css')), false)
})

test('tokens command prints machine-readable starter surface', () => {
  const output = run(['tokens', '--json'])
  const tokens = JSON.parse(output)

  assert.ok(tokens.themePresets.includes('neutral-saas'))
  assert.ok(tokens.starterClasses.layout.includes('sf-split'))
  assert.ok(tokens.starterClasses.layout.includes('sf-scroll-panel'))
  assert.ok(tokens.starterClasses.components.includes('sf-section-header'))
  assert.ok(tokens.starterClasses.components.includes('sf-dialog'))
  assert.ok(tokens.starterClasses.components.includes('sf-tooltip'))
  assert.ok(tokens.starterClasses.components.includes('sf-tabs'))
  assert.ok(tokens.starterClasses.utilities.includes('sr-only'))
  assert.ok(tokens.starterClasses.utilities.includes('sf-skip-link'))
  assert.ok(tokens.starterClasses.utilities.includes('sf-link-plain'))
  assert.ok(tokens.starterClasses.utilities.includes('sf-animate-rise'))
  assert.ok(tokens.colours.semantic.includes('primary'))
})

test('catalog command prints public API for AI composition', () => {
  const output = run(['catalog', '--json'])
  const catalog = JSON.parse(output)

  assert.ok(catalog.commands.includes('suggest'))
  assert.ok(catalog.commands.includes('recipe'))
  assert.ok(catalog.commands.includes('theme init'))
  assert.ok(catalog.patterns.some((pattern) => pattern.id === 'scroll-snap-page'))
  assert.ok(catalog.patterns.some((pattern) => pattern.classes.includes('sf-dialog')))
  assert.ok(catalog.recipes.some((recipe) => recipe.id === 'saas-landing'))
  assert.ok(catalog.recipes.some((recipe) => recipe.id === 'coming-soon'))
})

test('suggest command returns matching recipes and classes', () => {
  const output = run(['suggest', 'full page scroll portfolio', '--json'])
  const result = JSON.parse(output)

  assert.equal(result.query, 'full page scroll portfolio')
  assert.equal(result.suggestions[0].id, 'scroll-snap-page')
  assert.ok(result.suggestions[0].classes.includes('sf-scroll-panel'))
  assert.equal(result.recipes[0].id, 'portfolio-scroll')
  assert.ok(result.recipes[0].markup.includes('sf-scroll-viewport'))
})

test('recipe command prints copy-ready recipe markup', () => {
  const output = run(['recipe', 'saas-landing', '--json'])
  const recipe = JSON.parse(output)

  assert.equal(recipe.id, 'saas-landing')
  assert.ok(recipe.sections.includes('hero-split'))
  assert.ok(recipe.markup.includes('sf-pricing-grid'))

  const textOutput = run(['recipe', 'coming-soon', '--markup'])
  assert.match(textOutput, /coming-soon: Coming soon page/)
  assert.match(textOutput, /sf-form sf-card/)

  const nextOutput = run(['recipe', 'portfolio-scroll', '--framework', 'next', '--markup'])
  assert.match(nextOutput, /export default function Page/)
  assert.match(nextOutput, /className="sf-scroll-viewport"/)

  const astroSection = run(['recipe', '--section', 'form', '--framework', 'astro', '--markup'])
  assert.match(astroSection, /import '\.\.\/styles\/synced-fluid\.css'/)
  assert.match(astroSection, /class="sf-form"/)
})

test('theme init converts a brief into a valid theme object', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'brief.md'), 'Modern B2B site. Slightly rounded. Inter system UI. Primary blue, accent green, raised cards, spacious sections.')

  const output = run(['theme', 'init', '--cwd', cwd, '--from', 'brief.md', '--preset-base', 'neutral-saas', '--json'])
  const result = JSON.parse(output)

  assert.match(result.summary, /primary/)
  assert.equal(result.presetBase, 'neutral-saas')
  assert.equal(result.theme.colours.primary, 'oklch(62% 0.19 252)')
  assert.equal(result.theme.colours.accent, 'oklch(62% 0.16 150)')
  assert.equal(result.theme.layout.containerMax, '76rem')
  assert.equal(result.theme.components.card.shadow, 'var(--shadow-md)')
})

test('theme init warns when a brief omits brand decisions', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'brief.md'), 'Simple website.')

  const output = run(['theme', 'init', '--cwd', cwd, '--from', 'brief.md', '--json'])
  const result = JSON.parse(output)

  assert.ok(result.warnings.some((warning) => warning.includes('primary colour')))
  assert.ok(result.warnings.some((warning) => warning.includes('density')))
  assert.equal(result.theme.colours.primary, 'oklch(68% 0.18 44)')
})

test('theme validate checks configured theme shape', () => {
  const cwd = tempProject()
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  theme: {
    fonts: { sans: 'ui-sans-serif, system-ui, sans-serif' },
    colours: { primary: 'oklch(62% 0.19 252)' },
  },
})
`
  )

  const output = run(['theme', 'validate', '--cwd', cwd])
  assert.match(output, /pass theme is valid/)
})

test('lint reports unsupported classes with nearest alternatives', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sf-buton text-prmary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
})
`
  )

  const result = spawnSync('node', [cli, 'lint', '--cwd', cwd], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /sf-buton.*sf-button/)
  assert.match(result.stderr, /text-prmary.*text-primary/)
})

test('doctor teaches missing scripts and unsupported classes', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="sf-buton"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `import { defineConfig } from '@synced/fluid/config'

export default defineConfig({
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
  failOnUnsupported: false,
  theme: {
    colours: { primary: 'oklch(62% 0.19 252)' },
  },
})
`
  )

  const output = run(['doctor', '--cwd', cwd])

  assert.match(output, /Add "fluid:lint": "synced-fluid lint"/)
  assert.match(output, /Unsupported class tokens were found/)
  assert.match(output, /failOnUnsupported is disabled/)
})

test('package exposes modular CSS layer files', () => {
  const pkg = JSON.parse(readFileSync(join(packageRoot, 'package.json'), 'utf8'))
  const files = ['tokens.css', 'reset.css', 'base.css', 'app.css', 'layout.css', 'components.css', 'utilities.css', 'styles.css']

  for (const file of files) {
    assert.equal(pkg.exports[`./${file}`], `./${file}`)
    assert.match(readFileSync(join(packageRoot, file), 'utf8'), /@layer reset, tokens, base, app, layout, components, utilities;/)
  }

  const baseCss = readFileSync(join(packageRoot, 'base.css'), 'utf8')
  const appCss = readFileSync(join(packageRoot, 'app.css'), 'utf8')
  const utilitiesCss = readFileSync(join(packageRoot, 'utilities.css'), 'utf8')
  assert.match(baseCss, /text-decoration-color: color-mix\(in oklch, currentColor 55%, transparent\)/)
  assert.doesNotMatch(baseCss, /:where\(a\) \{ color: inherit; text-decoration: none;/)
  assert.match(appCss, /@layer app/)
  assert.match(appCss, /text-decoration: none/)
  assert.match(appCss, /list-style: none/)
  assert.match(utilitiesCss, /:where\(\.sf-visually-hidden, \.sr-only\)/)
  assert.match(utilitiesCss, /\.sf-skip-link/)
  assert.match(utilitiesCss, /\.sf-list-reset/)
  assert.match(utilitiesCss, /\.sf-link-plain/)
  assert.match(utilitiesCss, /\.sf-animate-rise/)

  const layoutCss = readFileSync(join(packageRoot, 'layout.css'), 'utf8')
  const componentsCss = readFileSync(join(packageRoot, 'components.css'), 'utf8')
  const tokensCss = readFileSync(join(packageRoot, 'tokens.css'), 'utf8')
  assert.match(tokensCss, /\.sf-theme-light/)
  assert.match(layoutCss, /\.sf-scroll-viewport/)
  assert.match(layoutCss, /\.sf-sticky-top/)
  assert.match(componentsCss, /\.sf-dialog/)
  assert.match(componentsCss, /\.sf-popover/)
  assert.match(componentsCss, /\.sf-drawer/)
  assert.match(componentsCss, /\.sf-tabs/)
})

test('package guardrails pass', () => {
  const output = execFileSync('node', ['scripts/guardrails.mjs'], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.match(output, /pass guardrails/)
})

test('invalid config fails with actionable errors', () => {
  const cwd = tempProject()
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: 'src',
  out: 42,
  responsiveVariants: 'yes',
  theme: {
    colours: ['bad'],
    layout: { columns: 0 },
  },
}
`
  )

  const result = spawnSync('node', [cli, 'build', '--cwd', cwd], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /Invalid Synced Fluid config/)
  assert.match(result.stderr, /scan must be an array of strings/)
  assert.match(result.stderr, /out must be a string/)
  assert.match(result.stderr, /responsiveVariants must be a boolean/)
  assert.match(result.stderr, /theme.colours must be an object/)
  assert.match(result.stderr, /theme.layout.columns must be a positive number/)
})

test('build creates missing output directories atomically', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="text-primary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['src'],
  out: 'generated/css/synced-fluid.css',
}
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'generated/css/synced-fluid.css'), 'utf8')
  assert.match(css, /Generated by @synced\/fluid/)
  assert.match(css, /\[class~="text-primary"\]\{color:var\(--color-primary\)\}/)
})

test('build scans WordPress PHP templates', () => {
  const cwd = tempProject()
  mkdirSync(join(cwd, 'templates'), { recursive: true })
  writeFileSync(join(cwd, 'templates/front-page.php'), '<section class="text-primary animate-pulse"></section>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['templates'],
  out: 'assets/css/synced-fluid.css',
  includeCore: true,
}
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'assets/css/synced-fluid.css'), 'utf8')
  assert.match(css, /\[class~="text-primary"\]\{color:var\(--color-primary\)\}/)
  assert.match(css, /@keyframes sf-pulse/)
})

test('build omits unused generated animation and gradient helpers', () => {
  const cwd = tempProject()
  writeFileSync(join(cwd, 'src/App.jsx'), '<div class="text-primary"></div>\n')
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['src'],
  out: 'src/synced-fluid.generated.css',
}
`
  )

  run(['build', '--cwd', cwd])

  const css = readFileSync(join(cwd, 'src/synced-fluid.generated.css'), 'utf8')
  assert.doesNotMatch(css, /@keyframes sf-pulse/)
  assert.doesNotMatch(css, /bg-gradient-to-r/)
})

test('runtime cx helper is dependency-free and handles common class values', async () => {
  const { cx } = await import(pathToFileURL(join(packageRoot, 'dist/index.js')).href)

  assert.equal(cx('sf-card', ['text-primary', false, ['font-bold']], { hidden: false, flex: true }), 'sf-card text-primary font-bold flex')
})

test('build warns about missing scan directories', () => {
  const cwd = tempProject()
  writeFileSync(
    join(cwd, 'synced-fluid.config.mjs'),
    `export default {
  scan: ['missing'],
  out: 'src/synced-fluid.generated.css',
}
`
  )

  const result = spawnSync('node', [cli, 'build', '--cwd', cwd, '--no-fail-on-unsupported'], {
    cwd: packageRoot,
    encoding: 'utf8',
  })

  assert.equal(result.status, 0)
  assert.match(result.stderr, /Scan directories not found: missing/)
})
